-- Create subjects table
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_code VARCHAR(20) UNIQUE NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  credits INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on course_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_subjects_course_id ON subjects(course_id);

-- Insert sample subjects for common courses
-- These can be modified or deleted as needed
